version: "3"
services:
   builder:
      image: "030399/test_spring_premetheus:${BRANCH_NAME:-main}"
      volumes:
         - ${REPO_PATH}:/root/.m2
         - ${DATA_PATH}/target:/deploy/application/target
      networks:
         - test_spring_premetheus
   app:
      build:
         context: ./deploy
      depends_on:
         - builder
      restart: on-failure
      volumes:
         - ${REPO_PATH}:/root/.m2
         - ${DATA_PATH}/target:/deploy/application/target
      environment:
         - NODE_NAME=${NODE_NAME:-localhost}
         - VERSION=${VERSION:-undefined}
      ports:
         - "${PORT:-8000}:${PORT:-8100}"
      networks:
         - test_spring_premetheus
      extra_hosts:
         - node9434:172.18.59.42
networks:
   test_spring_premetheus:
      external: true
